// Kept self-contained: the client build injects this factory with .toString().
export function createGroupUI(React,h,api,TeamUI={}) {
  const labelOf=group=>group.name||"未命名群組";
  const localRead=key=>{try{if(typeof localStorage==="undefined")return null;const value=localStorage.getItem(key);return value?JSON.parse(value):null;}catch{return null;}};
  const localWrite=(key,value)=>{try{if(typeof localStorage==="undefined")return false;localStorage.setItem(key,JSON.stringify(value));return true;}catch{return false;}};
  const localClear=(key,operationId)=>{try{if(typeof localStorage==="undefined")return false;if(operationId){const value=localRead(key);if((value?.pendingBody??value?.body)?.operationId!==operationId)return false;}localStorage.removeItem(key);return true;}catch{return false;}};
  const actionLabels={archive:"收存",trash:"移至回收區",restore:"恢復群組",pin:"置頂",unpin:"取消置頂"};
  function GroupHome({groups=[],drafts=[],onOpenGroup,onNewGroup,onNewConversation,onDraft,onSettings,onRefresh}) {
    const cacheKey="dcl:group-lifecycle:pending";
    const restored=React.useRef(localRead(cacheKey));
    const saved=restored.current?.schema===1&&restored.current.group?.id===restored.current.groupId&&restored.current.body?.operationId&&actionLabels[restored.current.body.action]?restored.current:null;
    const [query,setQuery]=React.useState(""),[view,setView]=React.useState("recent"),[preview,setPreview]=React.useState(()=>saved?{group:saved.group,action:saved.body.action,activity:saved.activity??{running:[],pending:[],monitors:[]},confirmPause:saved.body.confirmPause===true}:null),[busy,setBusy]=React.useState(false),[issue,setIssue]=React.useState(""),[pending,setPending]=React.useState(Boolean(saved)),[notice,setNotice]=React.useState(saved?"已恢復尚未確認的群組操作；請核對原結果。":""),[changes,setChanges]=React.useState({}),[cacheError,setCacheError]=React.useState("");
    const alive=React.useRef(true),sequence=React.useRef(0),busyRef=React.useRef(false),receipt=React.useRef(saved?{groupId:saved.groupId,body:saved.body}:null);
    React.useEffect(()=>{alive.current=true;return()=>{alive.current=false;sequence.current++;};},[]);
    const begin=async(group,action)=>{
      if(busyRef.current||receipt.current)return;busyRef.current=true;setBusy(true);setIssue("");setPreview({group,action});const request=++sequence.current;
      try{
        const current=(await api("/groups")).find(item=>item.id===group.id);
        if(!current)throw new Error("群組已不存在，請重新整理。");
        const activity=["archive","trash"].includes(action)?await api(`/groups/${encodeURIComponent(group.id)}/activity`):{running:[],pending:[],monitors:[]};
        if(!activity||!["running","pending","monitors"].every(key=>Array.isArray(activity[key])))throw new Error("未取得完整活動狀態；不會收存群組，請重新檢查。");
        if(alive.current&&request===sequence.current){const value={group:current,action,activity,confirmPause:false};setPreview(value);if(action==="pin"||action==="unpin")await perform(value,true);}
      }catch(cause){if(alive.current&&request===sequence.current)setIssue(cause.message??String(cause));}
      finally{busyRef.current=false;if(alive.current&&request===sequence.current)setBusy(false);}
    };
    const blocked=Boolean(preview?.activity&&(preview.activity.running.length||preview.activity.pending.length));
    const perform=async(value=preview,prepared=false)=>{
      if(busyRef.current&&!prepared||!value||!receipt.current&&(!value.activity||value.activity.running.length||value.activity.pending.length||value.activity.monitors.length&&!value.confirmPause))return;
      busyRef.current=true;setBusy(true);setIssue("");
      receipt.current??={groupId:value.group.id,body:{action:value.action,expectedRevision:value.group.revision,operationId:crypto.randomUUID(),confirmPause:value.confirmPause===true}};
      const request=receipt.current;
      if(!localWrite(cacheKey,{schema:1,...request,group:value.group,activity:value.activity}))setCacheError("本機未能暫存操作憑據；請留在此頁核對結果，重新載入可能遺失核對入口。");else setCacheError("");
      try{
        const result=await api(`/groups/${encodeURIComponent(request.groupId)}/lifecycle`,{method:"POST",body:JSON.stringify(request.body)});
        const cleared=localClear(cacheKey,request.body.operationId);
        if(alive.current){receipt.current=null;setPending(false);setCacheError(cleared?"":"操作已完成，但本機舊憑據未能清理；再次進入時請核對。");setChanges(old=>({...old,[result.id]:result}));setPreview(null);if(request.body.action==="restore")setView("recent");setNotice(`${actionLabels[request.body.action]}完成：「${labelOf(result)}」。${["archive","trash","restore"].includes(request.body.action)?"歷史保留；不會重啟監測、排程或舊任務。":""}`);try{await onRefresh?.();}catch{if(alive.current)setNotice("操作已保存；列表尚未同步，請重新整理。不要重做此操作。");}}
      }catch(cause){if(alive.current){if(cause.status===400||cause.status===409){localClear(cacheKey,request.body.operationId);receipt.current=null;setPending(false);setPreview(old=>({...old,activity:null,confirmPause:false}));}else setPending(true);setIssue(cause.message??String(cause));}}
      finally{busyRef.current=false;if(alive.current)setBusy(false);}
    };
    const currentGroups=groups.map(group=>{const change=changes[group.id];return change&&change.revision>=(group.revision??0)?{...group,...change,archivedAt:change.archivedAt,deletedAt:change.deletedAt,pinnedAt:change.pinnedAt}:group;});
    const visible=currentGroups.filter(group=>view==="archived"?group.archivedAt&&!group.deletedAt:view==="trash"?group.deletedAt:!group.archivedAt&&!group.deletedAt&&(view!=="pinned"||group.pinnedAt)).filter(group=>labelOf(group).toLocaleLowerCase().includes(query.trim().toLocaleLowerCase())).sort((a,b)=>Number(Boolean(b.pinnedAt))-Number(Boolean(a.pinnedAt))||(b.lastActivityAt??b.updatedAt??b.createdAt??0)-(a.lastActivityAt??a.updatedAt??a.createdAt??0));
    const groupDrafts=drafts.filter(draft=>draft.kind==="group"&&!draft.discardedAt&&!draft.groupCreatedId&&!draft.startedRoomId);
    const conversationDrafts=drafts.filter(draft=>draft.kind==="conversation"&&!draft.discardedAt&&!draft.groupCreatedId&&!draft.startedRoomId).sort((a,b)=>(b.lastActivityAt??b.updatedAt??b.createdAt??0)-(a.lastActivityAt??a.updatedAt??a.createdAt??0));
    return h("main",{className:"dclGroupHome","aria-label":"群組"},
      h("header",{className:"dclGroupHeader"},h("div",null,h("h2",null,"群組"),h("p",null,"選擇一支團隊，或從空白開始組隊。")),h("div",{className:"dclGroupActions"},h("button",{className:"dclSecondary",onClick:()=>onNewConversation?.()},"臨時對話"),h("button",{className:"dclPrimary",onClick:onNewGroup},"新建群組"))),
      h("p",{className:"dclGroupHint"},"臨時對話不需先建立群組；可以直接開始，再按需要組隊。"),
      notice?h("p",{className:"dclGroupNotice",role:"status"},notice):null,
      cacheError?h("p",{className:"dclGroupError",role:"alert"},cacheError):null,
      h("div",{className:"dclGroupToolbar"},h("input",{className:"dclInput",type:"search",value:query,"aria-label":"搜尋群組",placeholder:"搜尋群組…",onChange:event=>setQuery(event.target.value)}),h("div",{className:"dclGroupFilters","aria-label":"群組篩選"},[["recent","最近"],["pinned","置頂"],["archived","已收存"],["trash","回收區"]].map(([id,name])=>h("button",{className:"dclSecondary",key:id,"aria-pressed":view===id,onClick:()=>setView(id)},name)))),
      h("section",{className:"dclGroupCards","aria-label":"群組清單"},visible.length?visible.map(group=>h("article",{className:"dclGroupCard",key:group.id},h("button",{className:"dclGroupOpen","aria-label":`開啟群組：${labelOf(group)}`,onClick:()=>onOpenGroup?.(group.id)},h("strong",null,labelOf(group)),h("span",null,group.conversationCount?`${group.conversationCount} 段對話`:"尚無對話"),group.runningCount?h("span",{className:"dclGroupRunning"},`${group.runningCount} 段協作中`):null),!group.archivedAt&&!group.deletedAt?h("button",{className:"dclSecondary","aria-label":`管理群組：${labelOf(group)}`,onClick:()=>onSettings?.(group)},"管理"):null,
        !group.archivedAt&&!group.deletedAt?h("button",{className:"dclSecondary",disabled:busy||pending,"aria-label":`${group.pinnedAt?"取消置頂":"置頂"}群組：${labelOf(group)}`,onClick:()=>void begin(group,group.pinnedAt?"unpin":"pin")},group.pinnedAt?"已置頂":"置頂"):null,
        h("details",{className:"dclGroupCardMore"},h("summary",null,"更多"),!group.archivedAt&&!group.deletedAt?h("button",{className:"dclSecondary",disabled:busy||pending,"aria-label":`收存群組：${labelOf(group)}`,onClick:()=>void begin(group,"archive")},"收存"):null,(group.archivedAt||group.deletedAt)?h("button",{className:"dclSecondary",disabled:busy||pending,"aria-label":`恢復群組：${labelOf(group)}`,onClick:()=>void begin(group,"restore")},"恢復群組"):null,!group.deletedAt?h("button",{className:"dclDanger",disabled:busy||pending,"aria-label":`移至回收區：${labelOf(group)}`,onClick:()=>void begin(group,"trash")},"移至回收區"):null))):h("p",{className:"dclGroupEmpty",role:"status"},query?"沒有符合搜尋的群組。":"這裡尚無群組。")),
      preview?h("section",{className:"dclGroupLifecycle","aria-label":"群組收存預覽"},h("h3",null,`${actionLabels[preview.action]}「${labelOf(preview.group)}」`),h("p",null,preview.action==="restore"?"恢復群組的顯示與可操作狀態；不會重啟監測、排程或舊任務。":preview.action==="trash"?"移至可恢復的群組回收區，不再新增派送；不刪文件或原生會話，也不刪其他群組的 Agent。":preview.action==="archive"?"從日常清單收存，不刪對話、Agent、原生會話或文件；之後可以恢復。":"只調整群組在清單的位置，不影響對話與執行。"),busy?h("p",{role:"status"},receipt.current?"正在保存操作…":"正在核對群組活動…"):null,issue?h("p",{className:"dclGroupError",role:"alert"},issue):null,blocked?h("div",{className:"dclGroupError",role:"alert"},"仍有執行或待派送工作；請先查看相關對話，完成後再整理。收存不會暗中停止工作。",[...preview.activity.running,...preview.activity.pending].map(item=>h("button",{className:"dclSecondary",key:item.id,"aria-label":`查看對話：${item.name??item.title}`,onClick:()=>onOpenGroup?.(preview.group.id,item.roomId??item.id)},`查看 ${item.name??item.title}`))):null,
        preview.activity?.monitors.length?h("div",{className:"dclGroupMonitors"},h("p",null,`另有 ${preview.activity.monitors.length} 項未來監測；收存時必須一併暫停。`),h("ul",null,preview.activity.monitors.map(item=>h("li",{key:`${item.roomId}:${item.id}`},item.title||"未命名監測"))),h("label",{className:"dclGroupCheck"},h("input",{type:"checkbox","aria-label":"確認暫停此群組的未來監測",checked:preview.confirmPause,disabled:busy||pending,onChange:event=>setPreview(old=>({...old,confirmPause:event.target.checked}))}),"確認暫停此群組的未來監測；恢復群組不會重啟。")):null,
        pending?h("div",{className:"dclGroupNotice",role:"status"},h("p",null,"操作結果尚未確認；先核對這次操作，保留原憑據，不重複提交不同內容。"),h("button",{className:"dclSecondary",disabled:busy,onClick:()=>void perform()},"核對並重試這次操作")):null,
        h("div",{className:"dclGroupActions"},h("button",{className:"dclSecondary",disabled:busy||pending,onClick:()=>setPreview(null)},"取消"),h("button",{className:"dclSecondary",disabled:busy||pending,onClick:()=>void begin(preview.group,preview.action)},"重新檢查"),h("button",{className:"dclPrimary",disabled:busy||pending||blocked||!preview.activity||Boolean(preview.activity.monitors.length&&!preview.confirmPause),onClick:()=>void perform()},`確認${actionLabels[preview.action]}`))):null,
      groupDrafts.length?h("section",{className:"dclGroupDrafts","aria-label":"群組草稿"},h("h3",null,"群組草稿"),groupDrafts.map(draft=>h("button",{className:"dclGroupDraft",key:draft.id,onClick:()=>onDraft?.(draft)},draft.title||"未命名群組草稿"))):null,
      conversationDrafts.length?h("details",{className:"dclGroupSection dclGroupConversationDrafts","aria-label":"對話草稿"},h("summary",null,`對話草稿 · ${conversationDrafts.length}`),h("p",{className:"dclGroupHint"},"尚未完成的對話保留在這裡；繼續草稿不會另建群組。"),conversationDrafts.map(draft=>{
        const text=String(draft.text??"").trim().replace(/\s+/gu," "),excerpt=text.length>100?`${text.slice(0,100)}…`:text;
        const title=String(draft.title??"").trim()||excerpt||"未命名對話草稿";
        const owner=draft.groupId?(groups.find(group=>group.id===draft.groupId)?.name??"原群組暫不可用"):"臨時對話";
        return h("button",{className:"dclGroupDraft dclGroupConversationDraft",key:draft.id,"aria-label":`${draft.start?"核對開始結果":"繼續對話草稿"}：${title}`,onClick:()=>onDraft?.(draft)},h("span",{className:"dclGroupDraftInfo"},h("strong",null,title),h("small",null,`${owner}${draft.start?" · 開始結果待核對":""}`),draft.title&&excerpt?h("span",{className:"dclGroupDraftExcerpt"},excerpt):null));
      })):null);
  }
  const modes={discuss_only:"只討論",read_only_audit:"只讀審閱",inherit_dsh:"遵循 DSH",workspace_write:"工作區修改",full_access:"完整權限"};
  const memberId=member=>member.id??member.membershipId??member.agentId;
  const settingsOf=(group,config=group.defaults??{})=>({name:group.name??"",members:structuredClone(config.members??[]),defaultParticipantIds:[...(config.defaultParticipantIds??[])],environment:structuredClone(config.environment??{cwd:"",overrides:{}}),charter:config.charter??"",autoDeliver:config.autoDeliver!==false,mode:config.mode??config.defaultActionMode??"inherit_dsh"});
  function GroupSettings({group,onClose,onSaved,TeamUI:customTeamUI}) {
    const team=customTeamUI??TeamUI;
    const [data,setData]=React.useState(null),[loading,setLoading]=React.useState(true),[busy,setBusy]=React.useState(false),[error,setError]=React.useState(""),[status,setStatus]=React.useState(""),[picker,setPicker]=React.useState(false),[pending,setPending]=React.useState(false),[conflict,setConflict]=React.useState(false),[latest,setLatest]=React.useState(null),[leaving,setLeaving]=React.useState(false),[cacheError,setCacheError]=React.useState("");
    const revision=React.useRef(group.revision),base=React.useRef(null),alive=React.useRef(true),busyRef=React.useRef(false),receipt=React.useRef(null),loadSequence=React.useRef(0),target=React.useRef(group.id),dataRef=React.useRef(null),restored=React.useRef(null);
    const storageKey=`dcl:group-settings:${group.id}`;
    target.current=group.id;
    const adopt=value=>{dataRef.current=value;setData(value);};
    const cache=(value=dataRef.current)=>{if(!value)return true;const ok=localWrite(storageKey,{schema:1,groupId:group.id,data:value,inputRevision:revision.current,base:base.current,pendingBody:receipt.current});setCacheError(ok?"":"本機暫存不可用；輸入尚在此頁，離開或重新載入可能遺失。請先保存或複製內容。");return ok;};
    const load=async(compare=false)=>{
      const sequence=++loadSequence.current;setLoading(true);setError("");
      try{
        const before=(await api("/groups")).find(item=>item.id===group.id);
        if(!before)throw new Error("群組已不存在；未修改任何設定。");
        const config=await api(`/groups/${encodeURIComponent(group.id)}/configuration?all=true`);
        const after=(await api("/groups")).find(item=>item.id===group.id);
        if(!after||before.revision!==after.revision)throw new Error("讀取時群組已更新，請重新載入。");
        if(alive.current&&sequence===loadSequence.current){const value=settingsOf(after,config);if(compare)setLatest({data:value,revision:after.revision});else if(restored.current){if(!receipt.current&&revision.current!==after.revision){setConflict(true);setLatest({data:value,revision:after.revision});setStatus("已恢復本機未保存修改；服務端有新版本，請比較。");}else setStatus(receipt.current?"已恢復待核對的保存；使用原憑據核對，不另建成員。":"已恢復本機未保存修改；尚未套用至群組。");}else{revision.current=after.revision;base.current=JSON.stringify(value);adopt(value);}}
      }catch(cause){if(alive.current&&sequence===loadSequence.current)setError(cause.message??String(cause));}
      finally{if(alive.current&&sequence===loadSequence.current)setLoading(false);}
    };
    React.useEffect(()=>{
      alive.current=true;busyRef.current=false;receipt.current=null;base.current=null;restored.current=null;adopt(null);setBusy(false);setPending(false);setConflict(false);setLatest(null);setPicker(false);setLeaving(false);setStatus("");setCacheError("");
      const saved=localRead(storageKey);
      if(saved?.schema===1&&saved.groupId===group.id&&saved.data&&Array.isArray(saved.data.members)&&Array.isArray(saved.data.defaultParticipantIds)&&Number.isFinite(saved.inputRevision)){
        restored.current=saved;revision.current=saved.inputRevision;base.current=saved.base??null;adopt(saved.data);receipt.current=saved.pendingBody??null;setPending(Boolean(receipt.current));
      }
      void load();return()=>{alive.current=false;loadSequence.current++;};
    },[group.id]);
    const update=patch=>{if(busyRef.current||receipt.current)return;const next={...dataRef.current,...patch};adopt(next);setStatus(cache(next)?"尚未保存 · 已暫存在本機":"尚未保存 · 本機暫存失敗");};
    const useMembers=input=>{const members=input.filter(member=>member.enabled!==false),ids=new Set(members.map(memberId));update({members,defaultParticipantIds:data.defaultParticipantIds.filter(id=>ids.has(id)),environment:{...data.environment,overrides:Object.fromEntries(Object.entries(data.environment.overrides??{}).filter(([id])=>ids.has(id))),...(data.environment.presetOverrides?{presetOverrides:Object.fromEntries(Object.entries(data.environment.presetOverrides).filter(([id])=>ids.has(id)))}:{})}});};
    const save=async()=>{
      if(busyRef.current||!data||loading||conflict)return;busyRef.current=true;setBusy(true);setError("");
      receipt.current??={...structuredClone(data),expectedRevision:revision.current,operationId:crypto.randomUUID()};
      cache();
      const body=receipt.current,savingGroupId=group.id,generation=loadSequence.current,current=()=>alive.current&&target.current===savingGroupId&&loadSequence.current===generation;
      try{const result=await api(`/groups/${encodeURIComponent(savingGroupId)}`,{method:"POST",body:JSON.stringify(body)});const cleared=localClear(storageKey,body.operationId);if(current()){receipt.current=null;restored.current=null;setPending(false);const value=settingsOf(result,{...body,...result.defaults});revision.current=result.revision;base.current=JSON.stringify(value);adopt(value);setCacheError(cleared?"":"設定已保存，但本機舊暫存未能清理；重新進入時請核對版本。");setStatus("已保存；只影響未來對話，不改既有對話，也未發送消息。");try{await onSaved?.(result);}catch{if(current())setStatus("群組設定已保存；列表尚未同步，請重新整理。");}}}
      catch(cause){if(current()){if(cause.status===400||cause.status===409){receipt.current=null;setPending(false);cache();}else setPending(true);if(cause.status===409){setConflict(true);setLatest(null);}setError(cause.message??String(cause));}}
      finally{if(current()){busyRef.current=false;setBusy(false);}}
    };
    const finishComparison=useMine=>{revision.current=latest.revision;base.current=JSON.stringify(latest.data);restored.current=null;if(!useMine){adopt(latest.data);if(!localClear(storageKey))setCacheError("已採用最新版本，但本機舊暫存未能清理；再次進入時請核對。");}else cache();setLatest(null);setConflict(false);setError("");setStatus(useMine?"已保留本機版本；按保存才會套用已比較的差異。":"已採用最新版本；沒有提交修改。");};
    const describe=(value,key)=>key==="members"?value.members.map(member=>[member.alias,member.role,member.model?.model].filter(Boolean).join(" · ")).join("；")||"無成員":key==="defaultParticipantIds"?value.defaultParticipantIds.map(id=>value.members.find(member=>memberId(member)===id)?.alias??id).join("、")||"無預選":key==="environment"?[value.environment.cwd||"未指定",...Object.entries(value.environment.overrides??{}).map(([id,path])=>`${value.members.find(member=>memberId(member)===id)?.alias??id}：${path}`),value.environment.agentPreset?`原生配置：${value.environment.agentPreset}`:null,...Object.entries(value.environment.presetOverrides??{}).map(([id,preset])=>`${id} 配置：${preset}`)].filter(Boolean).join("；"):key==="autoDeliver"?value.autoDeliver?"開啟":"關閉":key==="mode"?modes[value.mode]??value.mode:value[key]||"（空白）";
    return h("section",{className:"dclGroupSettings","aria-label":`群組設定：${labelOf(group)}`,"aria-busy":busy||loading},
      h("header",{className:"dclGroupHeader"},h("div",null,h("h2",null,"群組設定"),h("p",null,"成員池與預選只影響未來對話；不改既有對話，不發送消息。")),h("button",{className:"dclSecondary",disabled:busy,onClick:()=>data&&(pending||JSON.stringify(data)!==base.current)?setLeaving(true):onClose?.()},"返回")),
      loading?h("p",{role:"status",className:"dclGroupEmpty"},"正在讀取群組設定…"):null,
      error?h("div",{className:"dclGroupError",role:"alert"},error,!data?h("button",{className:"dclSecondary",disabled:loading,onClick:()=>void load()},"重新載入設定"):null):null,
      cacheError?h("p",{className:"dclGroupError",role:"alert"},cacheError):null,
      pending?h("div",{className:"dclGroupNotice",role:"status"},h("p",null,"保存結果尚未確認；輸入保持不變，請先核對這次保存，不會另建重複成員。"),h("button",{className:"dclSecondary",disabled:busy,onClick:()=>void save()},"核對並重試這次保存")):null,
      conflict?h("section",{className:"dclGroupConflict","aria-label":"群組設定版本衝突"},h("h3",null,"群組在別處更新；你的輸入仍保留"),h("button",{className:"dclSecondary",disabled:loading,onClick:()=>void load(true)},"讀取最新版本並比較"),latest?h(React.Fragment,null,h("div",{className:"dclGroupComparison"},h("table",null,h("thead",null,h("tr",null,h("th",null,"設定"),h("th",null,"我的未保存修改"),h("th",null,"最新版本"))),h("tbody",null,[["name","名稱"],["members","成員池"],["defaultParticipantIds","新對話預選"],["environment","工作環境"],["charter","共同約定"],["autoDeliver","自動協作"],["mode","權限偏好"]].filter(([key])=>JSON.stringify(data[key])!==JSON.stringify(latest.data[key])).map(([key,label])=>h("tr",{key},h("th",{scope:"row"},label),h("td",null,describe(data,key)),h("td",null,describe(latest.data,key))))))),h("button",{className:"dclSecondary",onClick:()=>finishComparison(false)},"採用最新版本，捨棄我的未保存修改"),h("button",{className:"dclSecondary",onClick:()=>finishComparison(true)},"保留我的設定，以上差異採用本機版本")):null):null,
      leaving?h("section",{className:"dclGroupNotice","aria-label":"確認離開群組設定"},h("p",null,pending?"保存結果仍待核對。可保留原憑據與輸入，下次進入繼續核對；不會取消已送出的保存。":"還有未保存的設定。可以保留到本機，之後回來繼續，或明確捨棄。"),h("button",{className:"dclSecondary",onClick:()=>setLeaving(false)},"繼續編輯"),h("button",{className:"dclSecondary",onClick:()=>{if(cache())onClose?.();}},"保留修改並返回"),!pending?h("button",{className:"dclDanger",onClick:()=>{if(localClear(storageKey))onClose?.();else setCacheError("未能清除本機暫存，尚未捨棄；請先繼續編輯或保存。");}},"返回並捨棄未保存修改"):null):null,
      data?h("fieldset",{className:"dclGroupForm",disabled:busy||pending},
        h("label",{className:"dclGroupField"},"群組名稱",h("input",{className:"dclInput","aria-label":"群組名稱",value:data.name,maxLength:120,disabled:busy,onChange:event=>update({name:event.target.value})})),
        h("section",{className:"dclGroupMembers","aria-label":"群組成員池"},h("div",{className:"dclGroupSectionHeader"},h("h3",null,`群組成員 · ${data.members.length}`),h("button",{className:"dclSecondary",disabled:busy||!team.ParticipantPicker,onClick:()=>setPicker(true)},"加入或調整成員")),h("p",null,"加入群組不會自動設為新對話預選；移出不影響既有對話。"),data.members.length?data.members.map(member=>h("article",{key:memberId(member),className:"dclGroupMember"},h("span",{className:"dclGroupAvatar","aria-hidden":true},(member.alias||"A").slice(0,1)),h("div",null,h("strong",null,member.alias||"未命名 Agent"),h("p",null,member.role||"尚未設定職務")),h("button",{className:"dclSecondary",disabled:busy,"aria-label":`移出群組：${member.alias}`,onClick:()=>useMembers(data.members.filter(item=>memberId(item)!==memberId(member)))},"移出"))):h("p",{className:"dclGroupEmpty"},"尚無成員。可以先保存空群組，之後再加入 Agent。")),
        h("section",{className:"dclGroupPreselection","aria-label":"新對話預選"},h("h3",null,`新對話預選 · ${data.defaultParticipantIds.length} 位`),h("p",null,"預選可以少於成員池；未勾選的人仍是群組成員。"),data.members.map(member=>h("label",{key:memberId(member),className:"dclGroupCheck"},h("input",{type:"checkbox","aria-label":`預選${member.alias}`,checked:data.defaultParticipantIds.includes(memberId(member)),disabled:busy,onChange:event=>update({defaultParticipantIds:event.target.checked?[...new Set([...data.defaultParticipantIds,memberId(member)])]:data.defaultParticipantIds.filter(id=>id!==memberId(member))})}),member.alias)),!data.defaultParticipantIds.length?h("p",{className:"dclGroupHint"},"新對話預設為零人；可先記筆記，再選擇參與者。"):null),
        h("details",{className:"dclGroupSection"},h("summary",null,"共同約定"),h("label",{className:"dclGroupField"},"供未來對話使用的共同約定",h("textarea",{className:"dclFormTextArea","aria-label":"群組共同約定",value:data.charter,disabled:busy,maxLength:20000,onChange:event=>update({charter:event.target.value})}))),
        h("details",{className:"dclGroupSection"},h("summary",null,"工作環境"),team.DirectoryField?h(team.DirectoryField,{label:"群組預設工作目錄",value:data.environment.cwd??"",disabled:busy||pending,onChange:value=>update({environment:{...data.environment,cwd:value}})}):h("label",{className:"dclGroupField"},"群組預設工作目錄",h("input",{className:"dclInput","aria-label":"群組預設工作目錄",value:data.environment.cwd??"",disabled:busy,placeholder:"貼上完整路徑（選擇器暫不可用）",onChange:event=>update({environment:{...data.environment,cwd:event.target.value}})})),Object.keys(data.environment.overrides??{}).length?h("div",{className:"dclGroupOverrides"},h("p",null,"下列成員另有工作目錄；只改群組目錄不會覆寫這些設定。"),h("ul",null,Object.entries(data.environment.overrides).map(([id,path])=>h("li",{key:id},`${data.members.find(member=>memberId(member)===id)?.alias??id}：${path}`))),h("button",{className:"dclSecondary",disabled:busy,onClick:()=>update({environment:{...data.environment,overrides:{}}})},"全部成員改用群組目錄")):null,h("p",{className:"dclGroupHint"},"保存目錄只是設定工作位置，不額外授予文件權限。")),
        h("details",{className:"dclGroupSection"},h("summary",null,`協作與權限 · ${modes[data.mode]??data.mode}`),h("label",{className:"dclGroupCheck"},h("input",{type:"checkbox","aria-label":"新對話預設自動協作",checked:data.autoDeliver,disabled:busy,onChange:event=>update({autoDeliver:event.target.checked})}),"新對話預設自動協作"),h("label",{className:"dclGroupField"},"未來對話的權限偏好",h("select",{className:"dclSelect","aria-label":"群組預設權限",value:data.mode,disabled:busy,onChange:event=>update({mode:event.target.value})},Object.entries(modes).map(([value,label])=>h("option",{value,key:value},label)))),h("p",{className:"dclGroupHint"},"这里只保存偏好；不修改現有原生會話。開始工作前仍核對實際範圍。")),
        h("footer",{className:"dclGroupActions"},h("span",{role:"status"},status),h("button",{className:"dclPrimary",disabled:busy||pending||conflict||!data.name.trim()||JSON.stringify(data)===base.current,onClick:()=>void save()},busy?"保存中…":"保存群組設定")),
        picker&&team.ParticipantPicker?h(team.ParticipantPicker,{members:data.members,groupMembers:data.members,target:{kind:"group-members",id:group.id},onClose:()=>setPicker(false),onApply:members=>{useMembers(members);setPicker(false);}}):null):null);
  }
  return {GroupHome,GroupSettings};
}
